import path from 'node:path';
import { existsSync, readdirSync } from 'node:fs';
import { afterAll, beforeAll, describe, it } from 'vitest';
import { Verifier, type VerifierOptions } from '@pact-foundation/pact';
import { createHash } from 'node:crypto';
import { listenApp } from '../../helpers/app-context.js';
import { resetDatabase } from '../../helpers/database.js';
import { prisma } from '../../../src/api/prisma.js';

const PACTS_DIR = path.resolve(process.cwd(), 'pacts');
const PROVIDER_NAME = 'UsersAPI';
const PROVIDER_VERSION = process.env.GIT_SHA ?? 'local';
const PROVIDER_BRANCH = process.env.GIT_BRANCH ?? 'local';
const BROKER_URL = process.env.PACT_BROKER_URL;
const BROKER_TOKEN = process.env.PACT_BROKER_TOKEN;
const SHOULD_PUBLISH = Boolean(BROKER_URL && BROKER_TOKEN);

const sha = (value: string): string => createHash('sha256').update(value).digest('hex');

async function seedDefaultUser(): Promise<void> {
  await prisma.user.upsert({
    where: { id: '00000000-0000-0000-0000-000000000002' },
    update: {
      email: 'mariana.castro@acme.test',
      name: 'Mariana Castro',
      role: 'user',
      lastLoginAt: new Date('2025-01-20T08:15:00.000Z'),
      loginCount: 7,
    },
    create: {
      id: '00000000-0000-0000-0000-000000000002',
      email: 'mariana.castro@acme.test',
      name: 'Mariana Castro',
      role: 'user',
      passwordHash: sha('Mc.92!staging-key'),
      lastLoginAt: new Date('2025-01-20T08:15:00.000Z'),
      loginCount: 7,
    },
  });
}

async function seedUserList(): Promise<void> {
  await resetDatabase();
  const baseUsers = [
    {
      id: '00000000-0000-0000-0000-000000000001',
      email: 'ricardo.menezes@acme.test',
      name: 'Ricardo Menezes',
      role: 'admin',
    },
    {
      id: '00000000-0000-0000-0000-000000000002',
      email: 'mariana.castro@acme.test',
      name: 'Mariana Castro',
      role: 'user',
    },
    {
      id: '00000000-0000-0000-0000-000000000003',
      email: 'visitor@acme.test',
      name: 'External Visitor',
      role: 'guest',
    },
    {
      id: '00000000-0000-0000-0000-000000000004',
      email: 'joao.batista@acme.test',
      name: 'Bob Mendes',
      role: 'user',
    },
  ];

  for (const user of baseUsers) {
    await prisma.user.create({
      data: {
        ...user,
        passwordHash: sha(`${user.role}123`),
        loginCount: 1,
        // fixed lastLoginAt so it matches the consumer iso8601DateTime matcher (which rejects null).
        lastLoginAt: new Date('2025-01-20T08:15:00.000Z'),
      },
    });
  }
}

async function clearTargetEmail(email: string): Promise<void> {
  await resetDatabase();
  await prisma.user.deleteMany({ where: { email } });
}

describe('Pact provider verification: UsersAPI', () => {
  let baseURL: string;
  let close: () => Promise<void>;

  beforeAll(async () => {
    const handle = await listenApp();
    baseURL = handle.url;
    close = handle.close;
  });

  afterAll(async () => {
    await close();
    await prisma.$disconnect();
  });

  it('honors every contract from the FrontendApp consumer', async () => {
    const options: VerifierOptions = {
      provider: PROVIDER_NAME,
      providerBaseUrl: baseURL,
      providerVersion: PROVIDER_VERSION,
      providerVersionBranch: PROVIDER_BRANCH,
      logLevel: 'warn',
      timeout: 60_000,
      stateHandlers: {
        'default user exists': async () => {
          await resetDatabase();
          await seedDefaultUser();
        },
        'users list exists': async () => {
          await seedUserList();
        },
        'no duplicate email for pact-new-user@example.com': async () => {
          await clearTargetEmail('pact-new-user@example.com');
        },
        'user does not exist': async () => {
          await resetDatabase();
        },
      },
    };

    if (SHOULD_PUBLISH) {
      options.pactBrokerUrl = BROKER_URL;
      options.pactBrokerToken = BROKER_TOKEN;
      options.publishVerificationResult = true;
      options.consumerVersionSelectors = [{ mainBranch: true }, { deployedOrReleased: true }];
    } else {
      // Local run: read the files from the pacts/ directory generated by the consumer tests.
      if (!existsSync(PACTS_DIR)) {
        throw new Error(
          `Pacts directory not found at ${PACTS_DIR}. Run npm run test:pact:consumer first.`,
        );
      }
      const files = readdirSync(PACTS_DIR)
        .filter((file) => file.endsWith('.json') && file.toLowerCase().includes('-usersapi'))
        .map((file) => path.join(PACTS_DIR, file));

      if (files.length === 0) {
        throw new Error(`No pact for ${PROVIDER_NAME} found in ${PACTS_DIR}.`);
      }
      options.pactUrls = files;
    }

    await new Verifier(options).verifyProvider();
  }, 120_000);
});
