import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import type { FastifyInstance } from 'fastify';
import Ajv, { type ValidateFunction } from 'ajv';
import addFormats from 'ajv-formats';
import OpenAPISchemaValidator from 'openapi-schema-validator';
import { buildApp } from '../../src/api/app.js';
import { resetDatabase, seedMinimal } from '../helpers/database.js';

// Fastify generates the OpenAPI 3 spec from the schemas declared on each route.
// We resolve refs manually because Ajv 8 does not follow cross-document refs by default
// and the spec uses the "#/components/schemas/Name" format.
type OpenApiSpec = {
  openapi: string;
  paths: Record<string, Record<string, PathOperation>>;
  components?: { schemas?: Record<string, unknown> };
};

type PathOperation = {
  responses: Record<string, ResponseObject>;
};

type ResponseObject = {
  content?: Record<string, { schema?: unknown }>;
};

type Spec = OpenApiSpec & { components: { schemas: Record<string, unknown> } };

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

/**
 * Recursively replaces any { $ref: '#/components/schemas/X' } with the referenced schema,
 * preserving the rest of the tree. We keep a set of visited refs to avoid loops in
 * self-referential schemas.
 */
function resolveSchema(spec: Spec, node: unknown, seen: Set<string> = new Set()): unknown {
  if (Array.isArray(node)) {
    return node.map((item) => resolveSchema(spec, item, seen));
  }
  if (!isRecord(node)) return node;

  if (typeof node['$ref'] === 'string') {
    const ref = node['$ref'];
    const match = ref.match(/^#\/components\/schemas\/(.+)$/);
    if (!match) {
      throw new Error(`unsupported ref outside #/components/schemas: ${ref}`);
    }
    const name = match[1]!;
    if (seen.has(name)) {
      // already resolved in this chain; return an empty object to avoid infinite recursion.
      return {};
    }
    const target = spec.components.schemas[name];
    if (!target) {
      throw new Error(`referenced schema not found: ${name}`);
    }
    const nextSeen = new Set(seen);
    nextSeen.add(name);
    return resolveSchema(spec, target, nextSeen);
  }

  const out: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(node)) {
    out[key] = resolveSchema(spec, value, seen);
  }
  return out;
}

interface Case {
  method: 'GET' | 'POST';
  path: string; // path in the spec, e.g. /users/{id}
  url: string; // real URL for inject
  expectedStatus: number;
  body?: unknown;
}

describe('Conformance with the OpenAPI spec generated by Fastify', () => {
  let app: FastifyInstance;
  let spec: Spec;
  let ajv: Ajv;

  beforeAll(async () => {
    app = await buildApp({ logger: false, rateLimitMax: 1_000_000 });
    await app.ready();

    const generated = app.swagger() as unknown as OpenApiSpec;
    spec = {
      ...generated,
      components: {
        schemas: generated.components?.schemas ?? {},
      },
    };

    ajv = new Ajv({ strict: false, allErrors: true });
    addFormats(ajv);

    await resetDatabase();
    await seedMinimal();
  });

  afterAll(async () => {
    await app.close();
  });

  it('the generated spec itself is valid according to the OpenAPI 3 validator', () => {
    const validator = new OpenAPISchemaValidator({ version: 3 });
    const result = validator.validate(spec as unknown as Parameters<typeof validator.validate>[0]);
    expect(result.errors, JSON.stringify(result.errors, null, 2)).toHaveLength(0);
  });

  it('declares the key routes under paths', () => {
    expect(spec.paths['/users']).toBeDefined();
    expect(spec.paths['/users/{id}']).toBeDefined();
    expect(spec.paths['/orders']).toBeDefined();
    expect(spec.paths['/orders/{id}']).toBeDefined();
    expect(spec.paths['/auth/login']).toBeDefined();
  });

  const cases: Case[] = [
    {
      method: 'GET',
      path: '/users',
      url: '/users',
      expectedStatus: 200,
    },
    {
      method: 'GET',
      path: '/users/{id}',
      url: '/users/00000000-0000-0000-0000-000000000002',
      expectedStatus: 200,
    },
    {
      method: 'GET',
      path: '/orders',
      url: '/orders',
      expectedStatus: 200,
    },
    {
      method: 'GET',
      path: '/orders/{id}',
      url: '/orders/10000000-0000-0000-0000-000000000001',
      expectedStatus: 200,
    },
    {
      method: 'POST',
      path: '/users',
      url: '/users',
      expectedStatus: 201,
      body: {
        email: `openapi-${Date.now()}@example.com`,
        name: 'OpenAPI Probe',
        password: 'strong-password-1234',
      },
    },
    {
      method: 'POST',
      path: '/auth/login',
      url: '/auth/login',
      expectedStatus: 200,
      body: { email: 'mariana.castro@acme.test', password: 'Mc.92!staging-key' },
    },
  ];

  it.each(cases)(
    'response of $method $path matches the schema declared in the spec',
    async (testCase) => {
      const response = await app.inject({
        method: testCase.method,
        url: testCase.url,
        ...(testCase.body ? { payload: testCase.body } : {}),
        headers: { 'content-type': 'application/json' },
      });

      expect(response.statusCode).toBe(testCase.expectedStatus);

      const operation =
        spec.paths[testCase.path]?.[testCase.method.toLowerCase() as 'get' | 'post'];
      expect(
        operation,
        `operation ${testCase.method} ${testCase.path} missing in the spec`,
      ).toBeDefined();

      const responseSpec = operation!.responses[String(testCase.expectedStatus)];
      expect(
        responseSpec,
        `spec does not declare response ${testCase.expectedStatus} for ${testCase.method} ${testCase.path}`,
      ).toBeDefined();

      const contentEntries = Object.entries(responseSpec!.content ?? {});
      expect(
        contentEntries.length,
        'response without content declared in the spec',
      ).toBeGreaterThan(0);

      const [declaredContentType, mediaTypeObject] = contentEntries[0]!;
      // Response Content-Type must match the main type in the spec.
      const actualContentType = String(response.headers['content-type'] ?? '').toLowerCase();
      expect(actualContentType).toContain(declaredContentType.split(';')[0]!.toLowerCase());

      const schema = resolveSchema(spec, mediaTypeObject.schema);
      const validate = ajv.compile(schema as object) as ValidateFunction;
      const body = response.json();
      const valid = validate(body);

      expect(
        valid,
        `body diverges from schema ${testCase.method} ${testCase.path} ${testCase.expectedStatus}: ${JSON.stringify(validate.errors, null, 2)}\nbody: ${JSON.stringify(body)}`,
      ).toBe(true);
    },
  );

  it('404 response of GET /users/{id} also follows the ErrorBody schema', async () => {
    const response = await app.inject({
      method: 'GET',
      url: '/users/00000000-0000-0000-0000-0000000000ff',
    });
    expect(response.statusCode).toBe(404);

    const responseSpec = spec.paths['/users/{id}']!['get']!.responses['404']!;
    const mediaType = Object.values(responseSpec.content ?? {})[0];
    expect(mediaType, 'spec should declare content for 404 on /users/{id}').toBeDefined();

    const schema = resolveSchema(spec, mediaType!.schema);
    const validate = ajv.compile(schema as object);
    const body = response.json();
    const valid = validate(body);

    expect(
      valid,
      `body 404 diverges from schema: ${JSON.stringify(validate.errors, null, 2)}\nbody: ${JSON.stringify(body)}`,
    ).toBe(true);
  });
});
